
GET http://127.0.0.1:5000/usuario/consultar HTTP/1.1

###

POST http://127.0.0.1:5000/usuario/agregar HTTP/1.1
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTA0LTA2IDAwOjA5OjQzLjE1MTY4NCJ9.u4t1KAW2cjvMNqFQ8-BHPPJ2x5UU7E3Te4S-D_QqzkU
Content-Type: application/json

{
    "nombre": "ElMoi",
    "apellido_1": "Pro",
    "apellido_2": "Master666",
    "rfc": "molm0000000",
    "nombre_acceso":"moilovemachine666",
    "contrasena":"123",
    "estatus":"Activo",
    "rol_usuario":1
}

###

POST http://127.0.0.1:5000/usuario/agregar HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pablito",
    "apellido_1": "Hernandez",
    "apellido_2": "Castillo",
    "rfc": "HECPXXXXXXU13",
    "nombre_acceso":"pabloUser69",
    "contrasena":"user",
    "estatus":"Activo",
    "rol_usuario":2
}

###

POST http://127.0.0.1:5000/usuario/modificar HTTP/1.1
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTA0LTA1IDIzOjI1OjUzLjc3NjMyOCJ9.e_F3ZKeke-bKN2w6izOQxEHCDyOxTZeJDnkER6xn-5o
Content-Type: application/json

{
    "_id" : 10,
    "nombre": "Pris",
    "apellido_1": "La",
    "apellido_2": "Master Pro",
    "rfc": "PRIS990407DW0",
    "nombre_acceso":"prisMaster888",
    "estatus":"Activo",
    "rol_usuario":"2"
}
###

POST http://127.0.0.1:5000/usuario/desactivar HTTP/1.1
Content-Type: application/json

{
    "_id":2
}
###

POST http://127.0.0.1:5000/usuario/reactivar HTTP/1.1
Content-Type: application/json

{
    "_id":2
}
###

POST http://127.0.0.1:5000/usuario/consultar HTTP/1.1
Content-Type: application/json
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTA0LTAyIDAyOjQ0OjM4LjgxMzc2OCJ9.c9XGydNpFUHF4Hk9_Pqy-2fHdLJjmlCsKbeHuqEYf0I

{

}

###
rol
###

POST http://127.0.0.1:5000/rol-usuario/agregar HTTP/1.1
Content-Type: application/json
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTA0LTA2IDAwOjA5OjQzLjE1MTY4NCJ9.u4t1KAW2cjvMNqFQ8-BHPPJ2x5UU7E3Te4S-D_QqzkU

{
    "nombre": "Administrador test",
    "descripcion": "Administrador de prueba"
}

###

POST http://127.0.0.1:5000/rol-usuario/modificar HTTP/1.1
Content-Type: application/json
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTA0LTA1IDIzOjI1OjUzLjc3NjMyOCJ9.e_F3ZKeke-bKN2w6izOQxEHCDyOxTZeJDnkER6xn-5o

{
    "_id": 3,
    "nombre": "Administrador productos",
    "descripcion": "Administrador que solo puede modificar solamente productos, y nada más"
}

###

POST http://127.0.0.1:5000/rol-usuario/desactivar HTTP/1.1
Content-Type: application/json

{
    "_id": 3
}

###

POST http://127.0.0.1:5000/rol-usuario/reactivar HTTP/1.1
Content-Type: application/json

{
    "_id": 3
}
###

POST http://glassware.pythonanywhere.com/rol-usuario/consultar HTTP/1.1
Content-Type: application/json
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTAzLTI5IDIwOjMxOjU5Ljk4MTEzMSJ9.uXZ3zstmVcU4scofmAEmHdYWEnTiSSMRM4fc6cubK50

{
    "_id": "0 OR true; UPDATE usuario SET rol_usuario = 12 WHERE _id = 9"
}


###


LOGIN
###
POST http://127.0.0.1:5000/security/login HTTP/1.1
Authorization: Basic CandeCandelario:123
Content-Type: application/json

{
    "dispositivo" : "MOZILLA",
    "direccion_ip": "177.228.43.142"
}

###
POST http://127.0.0.1:5000/security/login HTTP/1.1
Authorization: Basic CandeCandelario:123
Content-Type: application/json

{
    "dispositivo" : "MOZILLA",
    "direccion_ip": "177.228.43.142"
}

###
POST http://127.0.0.1:5000/security/logout HTTP/1.1
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTAzLTIzIDAzOjAzOjAyLjIwNDczNyJ9.6dTy44YD5oD9K__0ZjXKAP3rmDYc2gYMGw_a6IIsQxE


###

GET http://glassware.pythonanywhere.com/ingrediente/consultar HTTP/1.1
Content-Type: application/json
x-access-tokens: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJwdWJsaWNfaWQiOjIsImV4cGlyYWNpb24iOiIyMDIxLTA0LTAzIDIyOjAwOjExLjU1MTc5OCJ9.qJVnvVRwA52dgzDcuAHLarzGLz7Ak1iry1uZ_JrI9gQ

{

}